// Code generated by go-swagger; DO NOT EDIT.

package issue_tracker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams creates a new GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams object
// with the default values initialized.
func NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams() *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithTimeout creates a new GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithTimeout(timeout time.Duration) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithContext creates a new GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithContext(ctx context.Context) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams{

		Context: ctx,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithHTTPClient creates a new GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesWorkspaceRepoSlugComponentsComponentIDParamsWithHTTPClient(client *http.Client) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams contains all the parameters to send to the API endpoint
for the get repositories workspace repo slug components component ID operation typically these are written to a http.Request
*/
type GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams struct {

	/*ComponentID
	  The component's id

	*/
	ComponentID int64
	/*RepoSlug
	  This can either be the repository slug or the UUID of the repository,
	surrounded by curly-braces, for example: `{repository UUID}`.


	*/
	RepoSlug string
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithTimeout(timeout time.Duration) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithContext(ctx context.Context) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithHTTPClient(client *http.Client) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentID adds the componentID to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithComponentID(componentID int64) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetComponentID(componentID int64) {
	o.ComponentID = componentID
}

// WithRepoSlug adds the repoSlug to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithRepoSlug(repoSlug string) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithWorkspace adds the workspace to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WithWorkspace(workspace string) *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the get repositories workspace repo slug components component ID params
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesWorkspaceRepoSlugComponentsComponentIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_id
	if err := r.SetPathParam("component_id", swag.FormatInt64(o.ComponentID)); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
