// Code generated by go-swagger; DO NOT EDIT.

package issue_tracker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams creates a new PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams object
// with the default values initialized.
func NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams() *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	var ()
	return &PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithTimeout creates a new PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithTimeout(timeout time.Duration) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	var ()
	return &PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams{

		timeout: timeout,
	}
}

// NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithContext creates a new PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithContext(ctx context.Context) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	var ()
	return &PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams{

		Context: ctx,
	}
}

// NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithHTTPClient creates a new PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParamsWithHTTPClient(client *http.Client) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	var ()
	return &PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams{
		HTTPClient: client,
	}
}

/*PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams contains all the parameters to send to the API endpoint
for the post repositories workspace repo slug issues issue ID comments operation typically these are written to a http.Request
*/
type PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams struct {

	/*Body
	  The new issue comment object.

	*/
	Body *models.IssueComment
	/*IssueID*/
	IssueID string
	/*RepoSlug
	  This can either be the repository slug or the UUID of the repository,
	surrounded by curly-braces, for example: `{repository UUID}`.


	*/
	RepoSlug string
	/*Username
	  This can either be the username or the UUID of the user,
	surrounded by curly-braces, for example: `{user UUID}`.


	*/
	Username string
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithTimeout(timeout time.Duration) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithContext(ctx context.Context) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithHTTPClient(client *http.Client) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithBody(body *models.IssueComment) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetBody(body *models.IssueComment) {
	o.Body = body
}

// WithIssueID adds the issueID to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithIssueID(issueID string) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetIssueID(issueID)
	return o
}

// SetIssueID adds the issueId to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetIssueID(issueID string) {
	o.IssueID = issueID
}

// WithRepoSlug adds the repoSlug to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithRepoSlug(repoSlug string) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithUsername adds the username to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithUsername(username string) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetUsername(username string) {
	o.Username = username
}

// WithWorkspace adds the workspace to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WithWorkspace(workspace string) *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the post repositories workspace repo slug issues issue ID comments params
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepositoriesWorkspaceRepoSlugIssuesIssueIDCommentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param issue_id
	if err := r.SetPathParam("issue_id", o.IssueID); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
