// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// NewPostTeamsUsernameProjectsParams creates a new PostTeamsUsernameProjectsParams object
// with the default values initialized.
func NewPostTeamsUsernameProjectsParams() *PostTeamsUsernameProjectsParams {
	var ()
	return &PostTeamsUsernameProjectsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostTeamsUsernameProjectsParamsWithTimeout creates a new PostTeamsUsernameProjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostTeamsUsernameProjectsParamsWithTimeout(timeout time.Duration) *PostTeamsUsernameProjectsParams {
	var ()
	return &PostTeamsUsernameProjectsParams{

		timeout: timeout,
	}
}

// NewPostTeamsUsernameProjectsParamsWithContext creates a new PostTeamsUsernameProjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostTeamsUsernameProjectsParamsWithContext(ctx context.Context) *PostTeamsUsernameProjectsParams {
	var ()
	return &PostTeamsUsernameProjectsParams{

		Context: ctx,
	}
}

// NewPostTeamsUsernameProjectsParamsWithHTTPClient creates a new PostTeamsUsernameProjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostTeamsUsernameProjectsParamsWithHTTPClient(client *http.Client) *PostTeamsUsernameProjectsParams {
	var ()
	return &PostTeamsUsernameProjectsParams{
		HTTPClient: client,
	}
}

/*PostTeamsUsernameProjectsParams contains all the parameters to send to the API endpoint
for the post teams username projects operation typically these are written to a http.Request
*/
type PostTeamsUsernameProjectsParams struct {

	/*Body*/
	Body *models.Project
	/*Username
	  This can either be the username or the UUID of the account,
	surrounded by curly-braces, for example: `{account UUID}`. An account
	is either a team or user.


	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) WithTimeout(timeout time.Duration) *PostTeamsUsernameProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) WithContext(ctx context.Context) *PostTeamsUsernameProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) WithHTTPClient(client *http.Client) *PostTeamsUsernameProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) WithBody(body *models.Project) *PostTeamsUsernameProjectsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) SetBody(body *models.Project) {
	o.Body = body
}

// WithUsername adds the username to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) WithUsername(username string) *PostTeamsUsernameProjectsParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the post teams username projects params
func (o *PostTeamsUsernameProjectsParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *PostTeamsUsernameProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
