// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// NewPostWorkspacesWorkspaceProjectsParams creates a new PostWorkspacesWorkspaceProjectsParams object
// with the default values initialized.
func NewPostWorkspacesWorkspaceProjectsParams() *PostWorkspacesWorkspaceProjectsParams {
	var ()
	return &PostWorkspacesWorkspaceProjectsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWorkspacesWorkspaceProjectsParamsWithTimeout creates a new PostWorkspacesWorkspaceProjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWorkspacesWorkspaceProjectsParamsWithTimeout(timeout time.Duration) *PostWorkspacesWorkspaceProjectsParams {
	var ()
	return &PostWorkspacesWorkspaceProjectsParams{

		timeout: timeout,
	}
}

// NewPostWorkspacesWorkspaceProjectsParamsWithContext creates a new PostWorkspacesWorkspaceProjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostWorkspacesWorkspaceProjectsParamsWithContext(ctx context.Context) *PostWorkspacesWorkspaceProjectsParams {
	var ()
	return &PostWorkspacesWorkspaceProjectsParams{

		Context: ctx,
	}
}

// NewPostWorkspacesWorkspaceProjectsParamsWithHTTPClient creates a new PostWorkspacesWorkspaceProjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostWorkspacesWorkspaceProjectsParamsWithHTTPClient(client *http.Client) *PostWorkspacesWorkspaceProjectsParams {
	var ()
	return &PostWorkspacesWorkspaceProjectsParams{
		HTTPClient: client,
	}
}

/*PostWorkspacesWorkspaceProjectsParams contains all the parameters to send to the API endpoint
for the post workspaces workspace projects operation typically these are written to a http.Request
*/
type PostWorkspacesWorkspaceProjectsParams struct {

	/*Body*/
	Body *models.Project
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) WithTimeout(timeout time.Duration) *PostWorkspacesWorkspaceProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) WithContext(ctx context.Context) *PostWorkspacesWorkspaceProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) WithHTTPClient(client *http.Client) *PostWorkspacesWorkspaceProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) WithBody(body *models.Project) *PostWorkspacesWorkspaceProjectsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) SetBody(body *models.Project) {
	o.Body = body
}

// WithWorkspace adds the workspace to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) WithWorkspace(workspace string) *PostWorkspacesWorkspaceProjectsParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the post workspaces workspace projects params
func (o *PostWorkspacesWorkspaceProjectsParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *PostWorkspacesWorkspaceProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
