// Code generated by go-swagger; DO NOT EDIT.

package pullrequests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsReader is a Reader for the GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommits structure.
type GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault creates a GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault with default headers values
func NewGetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault(code int) *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault {
	return &GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault{
		_statusCode: code,
	}
}

/*GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault handles this case with default header values.

Unexpected error.
*/
type GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get repositories workspace repo slug pullrequests pull request ID commits default response
func (o *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault) Code() int {
	return o._statusCode
}

func (o *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault) Error() string {
	return fmt.Sprintf("[GET /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits][%d] GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommits default  %+v", o._statusCode, o.Payload)
}

func (o *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDCommitsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
