// Code generated by go-swagger; DO NOT EDIT.

package pullrequests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveReader is a Reader for the PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApprove structure.
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK creates a PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK with default headers values
func NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK() *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK {
	return &PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK{}
}

/*PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK handles this case with default header values.

The `participant` object recording that the authenticated user approved the pull request.
*/
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK struct {
	Payload *models.Participant
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK) Error() string {
	return fmt.Sprintf("[POST /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve][%d] postRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIdApproveOK  %+v", 200, o.Payload)
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK) GetPayload() *models.Participant {
	return o.Payload
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Participant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized creates a PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized with default headers values
func NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized() *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized {
	return &PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized{}
}

/*PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized handles this case with default header values.

The request wasn't authenticated.
*/
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized struct {
	Payload *models.Error
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized) Error() string {
	return fmt.Sprintf("[POST /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve][%d] postRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIdApproveUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound creates a PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound with default headers values
func NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound() *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound {
	return &PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound{}
}

/*PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound handles this case with default header values.

The specified pull request or the repository does not exist.
*/
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound struct {
	Payload *models.Error
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound) Error() string {
	return fmt.Sprintf("[POST /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve][%d] postRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIdApproveNotFound  %+v", 404, o.Payload)
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDApproveNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
