// Code generated by go-swagger; DO NOT EDIT.

package pullrequests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineReader is a Reader for the PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDecline structure.
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 555:
		result := NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK creates a PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK with default headers values
func NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK() *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK {
	return &PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK{}
}

/*PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK handles this case with default header values.

The pull request object.
*/
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK struct {
	Payload *models.Pullrequest
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK) Error() string {
	return fmt.Sprintf("[POST /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline][%d] postRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIdDeclineOK  %+v", 200, o.Payload)
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK) GetPayload() *models.Pullrequest {
	return o.Payload
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Pullrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555 creates a PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555 with default headers values
func NewPostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555() *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555 {
	return &PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555{}
}

/*PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555 handles this case with default header values.

If the decline took too long and timed out.
In this case the caller should retry the request later.
*/
type PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555 struct {
	Payload *models.Error
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555) Error() string {
	return fmt.Sprintf("[POST /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline][%d] postRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIdDeclineStatus555  %+v", 555, o.Payload)
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostRepositoriesWorkspaceRepoSlugPullrequestsPullRequestIDDeclineStatus555) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
