// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteUsersUsernameHooksUIDParams creates a new DeleteUsersUsernameHooksUIDParams object
// with the default values initialized.
func NewDeleteUsersUsernameHooksUIDParams() *DeleteUsersUsernameHooksUIDParams {
	var ()
	return &DeleteUsersUsernameHooksUIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUsersUsernameHooksUIDParamsWithTimeout creates a new DeleteUsersUsernameHooksUIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUsersUsernameHooksUIDParamsWithTimeout(timeout time.Duration) *DeleteUsersUsernameHooksUIDParams {
	var ()
	return &DeleteUsersUsernameHooksUIDParams{

		timeout: timeout,
	}
}

// NewDeleteUsersUsernameHooksUIDParamsWithContext creates a new DeleteUsersUsernameHooksUIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUsersUsernameHooksUIDParamsWithContext(ctx context.Context) *DeleteUsersUsernameHooksUIDParams {
	var ()
	return &DeleteUsersUsernameHooksUIDParams{

		Context: ctx,
	}
}

// NewDeleteUsersUsernameHooksUIDParamsWithHTTPClient creates a new DeleteUsersUsernameHooksUIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUsersUsernameHooksUIDParamsWithHTTPClient(client *http.Client) *DeleteUsersUsernameHooksUIDParams {
	var ()
	return &DeleteUsersUsernameHooksUIDParams{
		HTTPClient: client,
	}
}

/*DeleteUsersUsernameHooksUIDParams contains all the parameters to send to the API endpoint
for the delete users username hooks UID operation typically these are written to a http.Request
*/
type DeleteUsersUsernameHooksUIDParams struct {

	/*UID
	  The installed webhook's id

	*/
	UID string
	/*Username
	  This can either be the username or the UUID of the account,
	surrounded by curly-braces, for example: `{account UUID}`. An account
	is either a team or user.


	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) WithTimeout(timeout time.Duration) *DeleteUsersUsernameHooksUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) WithContext(ctx context.Context) *DeleteUsersUsernameHooksUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) WithHTTPClient(client *http.Client) *DeleteUsersUsernameHooksUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) WithUID(uid string) *DeleteUsersUsernameHooksUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WithUsername adds the username to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) WithUsername(username string) *DeleteUsersUsernameHooksUIDParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete users username hooks UID params
func (o *DeleteUsersUsernameHooksUIDParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUsersUsernameHooksUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
