// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// DeleteUsersUsernameHooksUIDReader is a Reader for the DeleteUsersUsernameHooksUID structure.
type DeleteUsersUsernameHooksUIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersUsernameHooksUIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteUsersUsernameHooksUIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteUsersUsernameHooksUIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteUsersUsernameHooksUIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUsersUsernameHooksUIDNoContent creates a DeleteUsersUsernameHooksUIDNoContent with default headers values
func NewDeleteUsersUsernameHooksUIDNoContent() *DeleteUsersUsernameHooksUIDNoContent {
	return &DeleteUsersUsernameHooksUIDNoContent{}
}

/*DeleteUsersUsernameHooksUIDNoContent handles this case with default header values.

When the webhook was deleted successfully
*/
type DeleteUsersUsernameHooksUIDNoContent struct {
}

func (o *DeleteUsersUsernameHooksUIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{username}/hooks/{uid}][%d] deleteUsersUsernameHooksUidNoContent ", 204)
}

func (o *DeleteUsersUsernameHooksUIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUsersUsernameHooksUIDForbidden creates a DeleteUsersUsernameHooksUIDForbidden with default headers values
func NewDeleteUsersUsernameHooksUIDForbidden() *DeleteUsersUsernameHooksUIDForbidden {
	return &DeleteUsersUsernameHooksUIDForbidden{}
}

/*DeleteUsersUsernameHooksUIDForbidden handles this case with default header values.

If the authenticated user does not have permission to delete the webhook.
*/
type DeleteUsersUsernameHooksUIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteUsersUsernameHooksUIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /users/{username}/hooks/{uid}][%d] deleteUsersUsernameHooksUidForbidden  %+v", 403, o.Payload)
}

func (o *DeleteUsersUsernameHooksUIDForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersUsernameHooksUIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteUsersUsernameHooksUIDNotFound creates a DeleteUsersUsernameHooksUIDNotFound with default headers values
func NewDeleteUsersUsernameHooksUIDNotFound() *DeleteUsersUsernameHooksUIDNotFound {
	return &DeleteUsersUsernameHooksUIDNotFound{}
}

/*DeleteUsersUsernameHooksUIDNotFound handles this case with default header values.

If the webhook or user does not exist.
*/
type DeleteUsersUsernameHooksUIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteUsersUsernameHooksUIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /users/{username}/hooks/{uid}][%d] deleteUsersUsernameHooksUidNotFound  %+v", 404, o.Payload)
}

func (o *DeleteUsersUsernameHooksUIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteUsersUsernameHooksUIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
