// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// GetUserPermissionsWorkspacesReader is a Reader for the GetUserPermissionsWorkspaces structure.
type GetUserPermissionsWorkspacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserPermissionsWorkspacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserPermissionsWorkspacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUserPermissionsWorkspacesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUserPermissionsWorkspacesOK creates a GetUserPermissionsWorkspacesOK with default headers values
func NewGetUserPermissionsWorkspacesOK() *GetUserPermissionsWorkspacesOK {
	return &GetUserPermissionsWorkspacesOK{}
}

/*GetUserPermissionsWorkspacesOK handles this case with default header values.

All of the workspace memberships for a user.
*/
type GetUserPermissionsWorkspacesOK struct {
	Payload *models.PaginatedWorkspaceMemberships
}

func (o *GetUserPermissionsWorkspacesOK) Error() string {
	return fmt.Sprintf("[GET /user/permissions/workspaces][%d] getUserPermissionsWorkspacesOK  %+v", 200, o.Payload)
}

func (o *GetUserPermissionsWorkspacesOK) GetPayload() *models.PaginatedWorkspaceMemberships {
	return o.Payload
}

func (o *GetUserPermissionsWorkspacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedWorkspaceMemberships)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserPermissionsWorkspacesUnauthorized creates a GetUserPermissionsWorkspacesUnauthorized with default headers values
func NewGetUserPermissionsWorkspacesUnauthorized() *GetUserPermissionsWorkspacesUnauthorized {
	return &GetUserPermissionsWorkspacesUnauthorized{}
}

/*GetUserPermissionsWorkspacesUnauthorized handles this case with default header values.

The request wasn't authenticated.
*/
type GetUserPermissionsWorkspacesUnauthorized struct {
	Payload *models.Error
}

func (o *GetUserPermissionsWorkspacesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /user/permissions/workspaces][%d] getUserPermissionsWorkspacesUnauthorized  %+v", 401, o.Payload)
}

func (o *GetUserPermissionsWorkspacesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetUserPermissionsWorkspacesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
