// Code generated by go-swagger; DO NOT EDIT.

package commits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams creates a new GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams object
// with the default values initialized.
func NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams() *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithTimeout creates a new GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithTimeout(timeout time.Duration) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithContext creates a new GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithContext(ctx context.Context) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams{

		Context: ctx,
	}
}

// NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithHTTPClient creates a new GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParamsWithHTTPClient(client *http.Client) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	var ()
	return &GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams contains all the parameters to send to the API endpoint
for the get repositories workspace repo slug commit node comments comment ID operation typically these are written to a http.Request
*/
type GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams struct {

	/*CommentID
	  The id of the comment.

	*/
	CommentID int64
	/*Node
	  The commit's SHA1.

	*/
	Node string
	/*RepoSlug
	  This can either be the repository slug or the UUID of the repository,
	surrounded by curly-braces, for example: `{repository UUID}`.


	*/
	RepoSlug string
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithTimeout(timeout time.Duration) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithContext(ctx context.Context) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithHTTPClient(client *http.Client) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommentID adds the commentID to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithCommentID(commentID int64) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetCommentID(commentID)
	return o
}

// SetCommentID adds the commentId to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetCommentID(commentID int64) {
	o.CommentID = commentID
}

// WithNode adds the node to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithNode(node string) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetNode(node string) {
	o.Node = node
}

// WithRepoSlug adds the repoSlug to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithRepoSlug(repoSlug string) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithWorkspace adds the workspace to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WithWorkspace(workspace string) *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the get repositories workspace repo slug commit node comments comment ID params
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesWorkspaceRepoSlugCommitNodeCommentsCommentIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param comment_id
	if err := r.SetPathParam("comment_id", swag.FormatInt64(o.CommentID)); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
