// Code generated by go-swagger; DO NOT EDIT.

package pipelines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDeploymentVariablesParams creates a new GetDeploymentVariablesParams object
// with the default values initialized.
func NewGetDeploymentVariablesParams() *GetDeploymentVariablesParams {
	var ()
	return &GetDeploymentVariablesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDeploymentVariablesParamsWithTimeout creates a new GetDeploymentVariablesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDeploymentVariablesParamsWithTimeout(timeout time.Duration) *GetDeploymentVariablesParams {
	var ()
	return &GetDeploymentVariablesParams{

		timeout: timeout,
	}
}

// NewGetDeploymentVariablesParamsWithContext creates a new GetDeploymentVariablesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDeploymentVariablesParamsWithContext(ctx context.Context) *GetDeploymentVariablesParams {
	var ()
	return &GetDeploymentVariablesParams{

		Context: ctx,
	}
}

// NewGetDeploymentVariablesParamsWithHTTPClient creates a new GetDeploymentVariablesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDeploymentVariablesParamsWithHTTPClient(client *http.Client) *GetDeploymentVariablesParams {
	var ()
	return &GetDeploymentVariablesParams{
		HTTPClient: client,
	}
}

/*GetDeploymentVariablesParams contains all the parameters to send to the API endpoint
for the get deployment variables operation typically these are written to a http.Request
*/
type GetDeploymentVariablesParams struct {

	/*EnvironmentUUID
	  The environment.

	*/
	EnvironmentUUID string
	/*RepoSlug
	  The repository.

	*/
	RepoSlug string
	/*Username
	  The account.

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithTimeout(timeout time.Duration) *GetDeploymentVariablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithContext(ctx context.Context) *GetDeploymentVariablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithHTTPClient(client *http.Client) *GetDeploymentVariablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentUUID adds the environmentUUID to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithEnvironmentUUID(environmentUUID string) *GetDeploymentVariablesParams {
	o.SetEnvironmentUUID(environmentUUID)
	return o
}

// SetEnvironmentUUID adds the environmentUuid to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetEnvironmentUUID(environmentUUID string) {
	o.EnvironmentUUID = environmentUUID
}

// WithRepoSlug adds the repoSlug to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithRepoSlug(repoSlug string) *GetDeploymentVariablesParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithUsername adds the username to the get deployment variables params
func (o *GetDeploymentVariablesParams) WithUsername(username string) *GetDeploymentVariablesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get deployment variables params
func (o *GetDeploymentVariablesParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *GetDeploymentVariablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environment_uuid
	if err := r.SetPathParam("environment_uuid", o.EnvironmentUUID); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
