// Code generated by go-swagger; DO NOT EDIT.

package snippets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// DeleteSnippetsWorkspaceEncodedIDReader is a Reader for the DeleteSnippetsWorkspaceEncodedID structure.
type DeleteSnippetsWorkspaceEncodedIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSnippetsWorkspaceEncodedIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSnippetsWorkspaceEncodedIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteSnippetsWorkspaceEncodedIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteSnippetsWorkspaceEncodedIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSnippetsWorkspaceEncodedIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSnippetsWorkspaceEncodedIDNoContent creates a DeleteSnippetsWorkspaceEncodedIDNoContent with default headers values
func NewDeleteSnippetsWorkspaceEncodedIDNoContent() *DeleteSnippetsWorkspaceEncodedIDNoContent {
	return &DeleteSnippetsWorkspaceEncodedIDNoContent{}
}

/*DeleteSnippetsWorkspaceEncodedIDNoContent handles this case with default header values.

If the snippet was deleted successfully.
*/
type DeleteSnippetsWorkspaceEncodedIDNoContent struct {
}

func (o *DeleteSnippetsWorkspaceEncodedIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /snippets/{workspace}/{encoded_id}][%d] deleteSnippetsWorkspaceEncodedIdNoContent ", 204)
}

func (o *DeleteSnippetsWorkspaceEncodedIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSnippetsWorkspaceEncodedIDUnauthorized creates a DeleteSnippetsWorkspaceEncodedIDUnauthorized with default headers values
func NewDeleteSnippetsWorkspaceEncodedIDUnauthorized() *DeleteSnippetsWorkspaceEncodedIDUnauthorized {
	return &DeleteSnippetsWorkspaceEncodedIDUnauthorized{}
}

/*DeleteSnippetsWorkspaceEncodedIDUnauthorized handles this case with default header values.

If the snippet is private and the request was not authenticated.
*/
type DeleteSnippetsWorkspaceEncodedIDUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteSnippetsWorkspaceEncodedIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /snippets/{workspace}/{encoded_id}][%d] deleteSnippetsWorkspaceEncodedIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteSnippetsWorkspaceEncodedIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSnippetsWorkspaceEncodedIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSnippetsWorkspaceEncodedIDForbidden creates a DeleteSnippetsWorkspaceEncodedIDForbidden with default headers values
func NewDeleteSnippetsWorkspaceEncodedIDForbidden() *DeleteSnippetsWorkspaceEncodedIDForbidden {
	return &DeleteSnippetsWorkspaceEncodedIDForbidden{}
}

/*DeleteSnippetsWorkspaceEncodedIDForbidden handles this case with default header values.

If authenticated user does not have permission to delete the private snippet.
*/
type DeleteSnippetsWorkspaceEncodedIDForbidden struct {
	Payload *models.Error
}

func (o *DeleteSnippetsWorkspaceEncodedIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /snippets/{workspace}/{encoded_id}][%d] deleteSnippetsWorkspaceEncodedIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteSnippetsWorkspaceEncodedIDForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSnippetsWorkspaceEncodedIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSnippetsWorkspaceEncodedIDNotFound creates a DeleteSnippetsWorkspaceEncodedIDNotFound with default headers values
func NewDeleteSnippetsWorkspaceEncodedIDNotFound() *DeleteSnippetsWorkspaceEncodedIDNotFound {
	return &DeleteSnippetsWorkspaceEncodedIDNotFound{}
}

/*DeleteSnippetsWorkspaceEncodedIDNotFound handles this case with default header values.

If the snippet does not exist.
*/
type DeleteSnippetsWorkspaceEncodedIDNotFound struct {
	Payload *models.Error
}

func (o *DeleteSnippetsWorkspaceEncodedIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /snippets/{workspace}/{encoded_id}][%d] deleteSnippetsWorkspaceEncodedIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteSnippetsWorkspaceEncodedIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSnippetsWorkspaceEncodedIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
