// Code generated by go-swagger; DO NOT EDIT.

package snippets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSnippetsWorkspaceParams creates a new GetSnippetsWorkspaceParams object
// with the default values initialized.
func NewGetSnippetsWorkspaceParams() *GetSnippetsWorkspaceParams {
	var ()
	return &GetSnippetsWorkspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSnippetsWorkspaceParamsWithTimeout creates a new GetSnippetsWorkspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSnippetsWorkspaceParamsWithTimeout(timeout time.Duration) *GetSnippetsWorkspaceParams {
	var ()
	return &GetSnippetsWorkspaceParams{

		timeout: timeout,
	}
}

// NewGetSnippetsWorkspaceParamsWithContext creates a new GetSnippetsWorkspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSnippetsWorkspaceParamsWithContext(ctx context.Context) *GetSnippetsWorkspaceParams {
	var ()
	return &GetSnippetsWorkspaceParams{

		Context: ctx,
	}
}

// NewGetSnippetsWorkspaceParamsWithHTTPClient creates a new GetSnippetsWorkspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSnippetsWorkspaceParamsWithHTTPClient(client *http.Client) *GetSnippetsWorkspaceParams {
	var ()
	return &GetSnippetsWorkspaceParams{
		HTTPClient: client,
	}
}

/*GetSnippetsWorkspaceParams contains all the parameters to send to the API endpoint
for the get snippets workspace operation typically these are written to a http.Request
*/
type GetSnippetsWorkspaceParams struct {

	/*Role
	  Filter down the result based on the authenticated user's role (`owner`, `contributor`, or `member`).

	*/
	Role *string
	/*Username
	  Limits the result to snippets owned by this user.

	*/
	Username string
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithTimeout(timeout time.Duration) *GetSnippetsWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithContext(ctx context.Context) *GetSnippetsWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithHTTPClient(client *http.Client) *GetSnippetsWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRole adds the role to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithRole(role *string) *GetSnippetsWorkspaceParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetRole(role *string) {
	o.Role = role
}

// WithUsername adds the username to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithUsername(username string) *GetSnippetsWorkspaceParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetUsername(username string) {
	o.Username = username
}

// WithWorkspace adds the workspace to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) WithWorkspace(workspace string) *GetSnippetsWorkspaceParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the get snippets workspace params
func (o *GetSnippetsWorkspaceParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *GetSnippetsWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Role != nil {

		// query param role
		var qrRole string
		if o.Role != nil {
			qrRole = *o.Role
		}
		qRole := qrRole
		if qRole != "" {
			if err := r.SetQueryParam("role", qRole); err != nil {
				return err
			}
		}

	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
