// Code generated by go-swagger; DO NOT EDIT.

package snippets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSnippetsWorkspaceEncodedIDNodeIDParams creates a new GetSnippetsWorkspaceEncodedIDNodeIDParams object
// with the default values initialized.
func NewGetSnippetsWorkspaceEncodedIDNodeIDParams() *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	var ()
	return &GetSnippetsWorkspaceEncodedIDNodeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithTimeout creates a new GetSnippetsWorkspaceEncodedIDNodeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithTimeout(timeout time.Duration) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	var ()
	return &GetSnippetsWorkspaceEncodedIDNodeIDParams{

		timeout: timeout,
	}
}

// NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithContext creates a new GetSnippetsWorkspaceEncodedIDNodeIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithContext(ctx context.Context) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	var ()
	return &GetSnippetsWorkspaceEncodedIDNodeIDParams{

		Context: ctx,
	}
}

// NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithHTTPClient creates a new GetSnippetsWorkspaceEncodedIDNodeIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSnippetsWorkspaceEncodedIDNodeIDParamsWithHTTPClient(client *http.Client) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	var ()
	return &GetSnippetsWorkspaceEncodedIDNodeIDParams{
		HTTPClient: client,
	}
}

/*GetSnippetsWorkspaceEncodedIDNodeIDParams contains all the parameters to send to the API endpoint
for the get snippets workspace encoded ID node ID operation typically these are written to a http.Request
*/
type GetSnippetsWorkspaceEncodedIDNodeIDParams struct {

	/*EncodedID
	  The snippet's id.

	*/
	EncodedID string
	/*NodeID
	  A commit revision (SHA1).

	*/
	NodeID string
	/*Workspace
	  This can either be the workspace ID (slug) or the workspace UUID
	surrounded by curly-braces, for example: `{workspace UUID}`.


	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithTimeout(timeout time.Duration) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithContext(ctx context.Context) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithHTTPClient(client *http.Client) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEncodedID adds the encodedID to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithEncodedID(encodedID string) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetEncodedID(encodedID)
	return o
}

// SetEncodedID adds the encodedId to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetEncodedID(encodedID string) {
	o.EncodedID = encodedID
}

// WithNodeID adds the nodeID to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithNodeID(nodeID string) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetNodeID(nodeID)
	return o
}

// SetNodeID adds the nodeId to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetNodeID(nodeID string) {
	o.NodeID = nodeID
}

// WithWorkspace adds the workspace to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WithWorkspace(workspace string) *GetSnippetsWorkspaceEncodedIDNodeIDParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the get snippets workspace encoded ID node ID params
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *GetSnippetsWorkspaceEncodedIDNodeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param encoded_id
	if err := r.SetPathParam("encoded_id", o.EncodedID); err != nil {
		return err
	}

	// path param node_id
	if err := r.SetPathParam("node_id", o.NodeID); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
