// Code generated by go-swagger; DO NOT EDIT.

package snippets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// PostSnippetsWorkspaceEncodedIDCommentsReader is a Reader for the PostSnippetsWorkspaceEncodedIDComments structure.
type PostSnippetsWorkspaceEncodedIDCommentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSnippetsWorkspaceEncodedIDCommentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostSnippetsWorkspaceEncodedIDCommentsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPostSnippetsWorkspaceEncodedIDCommentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostSnippetsWorkspaceEncodedIDCommentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostSnippetsWorkspaceEncodedIDCommentsCreated creates a PostSnippetsWorkspaceEncodedIDCommentsCreated with default headers values
func NewPostSnippetsWorkspaceEncodedIDCommentsCreated() *PostSnippetsWorkspaceEncodedIDCommentsCreated {
	return &PostSnippetsWorkspaceEncodedIDCommentsCreated{}
}

/*PostSnippetsWorkspaceEncodedIDCommentsCreated handles this case with default header values.

The newly created comment.
*/
type PostSnippetsWorkspaceEncodedIDCommentsCreated struct {
	/*The URL of the new comment
	 */
	Location string

	Payload *models.Snippet
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsCreated) Error() string {
	return fmt.Sprintf("[POST /snippets/{workspace}/{encoded_id}/comments][%d] postSnippetsWorkspaceEncodedIdCommentsCreated  %+v", 201, o.Payload)
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsCreated) GetPayload() *models.Snippet {
	return o.Payload
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Location
	o.Location = response.GetHeader("Location")

	o.Payload = new(models.Snippet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSnippetsWorkspaceEncodedIDCommentsForbidden creates a PostSnippetsWorkspaceEncodedIDCommentsForbidden with default headers values
func NewPostSnippetsWorkspaceEncodedIDCommentsForbidden() *PostSnippetsWorkspaceEncodedIDCommentsForbidden {
	return &PostSnippetsWorkspaceEncodedIDCommentsForbidden{}
}

/*PostSnippetsWorkspaceEncodedIDCommentsForbidden handles this case with default header values.

If the authenticated user does not have access to the snippet.
*/
type PostSnippetsWorkspaceEncodedIDCommentsForbidden struct {
	Payload *models.Error
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsForbidden) Error() string {
	return fmt.Sprintf("[POST /snippets/{workspace}/{encoded_id}/comments][%d] postSnippetsWorkspaceEncodedIdCommentsForbidden  %+v", 403, o.Payload)
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSnippetsWorkspaceEncodedIDCommentsNotFound creates a PostSnippetsWorkspaceEncodedIDCommentsNotFound with default headers values
func NewPostSnippetsWorkspaceEncodedIDCommentsNotFound() *PostSnippetsWorkspaceEncodedIDCommentsNotFound {
	return &PostSnippetsWorkspaceEncodedIDCommentsNotFound{}
}

/*PostSnippetsWorkspaceEncodedIDCommentsNotFound handles this case with default header values.

If the snippet does not exist.
*/
type PostSnippetsWorkspaceEncodedIDCommentsNotFound struct {
	Payload *models.Error
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsNotFound) Error() string {
	return fmt.Sprintf("[POST /snippets/{workspace}/{encoded_id}/comments][%d] postSnippetsWorkspaceEncodedIdCommentsNotFound  %+v", 404, o.Payload)
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostSnippetsWorkspaceEncodedIDCommentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
