// Code generated by go-swagger; DO NOT EDIT.

package properties

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateRepositoryHostedPropertyValueParams creates a new UpdateRepositoryHostedPropertyValueParams object
// with the default values initialized.
func NewUpdateRepositoryHostedPropertyValueParams() *UpdateRepositoryHostedPropertyValueParams {
	var ()
	return &UpdateRepositoryHostedPropertyValueParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepositoryHostedPropertyValueParamsWithTimeout creates a new UpdateRepositoryHostedPropertyValueParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRepositoryHostedPropertyValueParamsWithTimeout(timeout time.Duration) *UpdateRepositoryHostedPropertyValueParams {
	var ()
	return &UpdateRepositoryHostedPropertyValueParams{

		timeout: timeout,
	}
}

// NewUpdateRepositoryHostedPropertyValueParamsWithContext creates a new UpdateRepositoryHostedPropertyValueParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRepositoryHostedPropertyValueParamsWithContext(ctx context.Context) *UpdateRepositoryHostedPropertyValueParams {
	var ()
	return &UpdateRepositoryHostedPropertyValueParams{

		Context: ctx,
	}
}

// NewUpdateRepositoryHostedPropertyValueParamsWithHTTPClient creates a new UpdateRepositoryHostedPropertyValueParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRepositoryHostedPropertyValueParamsWithHTTPClient(client *http.Client) *UpdateRepositoryHostedPropertyValueParams {
	var ()
	return &UpdateRepositoryHostedPropertyValueParams{
		HTTPClient: client,
	}
}

/*UpdateRepositoryHostedPropertyValueParams contains all the parameters to send to the API endpoint
for the update repository hosted property value operation typically these are written to a http.Request
*/
type UpdateRepositoryHostedPropertyValueParams struct {

	/*AppKey
	  The key of the Connect app.

	*/
	AppKey string
	/*PropertyName
	  The name of the property.

	*/
	PropertyName string
	/*RepoSlug
	  The repository.

	*/
	RepoSlug string
	/*Workspace
	  The repository container; either the workspace slug or the UUID in curly braces.

	*/
	Workspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithTimeout(timeout time.Duration) *UpdateRepositoryHostedPropertyValueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithContext(ctx context.Context) *UpdateRepositoryHostedPropertyValueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithHTTPClient(client *http.Client) *UpdateRepositoryHostedPropertyValueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppKey adds the appKey to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithAppKey(appKey string) *UpdateRepositoryHostedPropertyValueParams {
	o.SetAppKey(appKey)
	return o
}

// SetAppKey adds the appKey to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetAppKey(appKey string) {
	o.AppKey = appKey
}

// WithPropertyName adds the propertyName to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithPropertyName(propertyName string) *UpdateRepositoryHostedPropertyValueParams {
	o.SetPropertyName(propertyName)
	return o
}

// SetPropertyName adds the propertyName to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetPropertyName(propertyName string) {
	o.PropertyName = propertyName
}

// WithRepoSlug adds the repoSlug to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithRepoSlug(repoSlug string) *UpdateRepositoryHostedPropertyValueParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithWorkspace adds the workspace to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) WithWorkspace(workspace string) *UpdateRepositoryHostedPropertyValueParams {
	o.SetWorkspace(workspace)
	return o
}

// SetWorkspace adds the workspace to the update repository hosted property value params
func (o *UpdateRepositoryHostedPropertyValueParams) SetWorkspace(workspace string) {
	o.Workspace = workspace
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepositoryHostedPropertyValueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_key
	if err := r.SetPathParam("app_key", o.AppKey); err != nil {
		return err
	}

	// path param property_name
	if err := r.SetPathParam("property_name", o.PropertyName); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param workspace
	if err := r.SetPathParam("workspace", o.Workspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
