// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentForRepositoryParams creates a new DeleteEnvironmentForRepositoryParams object
// with the default values initialized.
func NewDeleteEnvironmentForRepositoryParams() *DeleteEnvironmentForRepositoryParams {
	var ()
	return &DeleteEnvironmentForRepositoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnvironmentForRepositoryParamsWithTimeout creates a new DeleteEnvironmentForRepositoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEnvironmentForRepositoryParamsWithTimeout(timeout time.Duration) *DeleteEnvironmentForRepositoryParams {
	var ()
	return &DeleteEnvironmentForRepositoryParams{

		timeout: timeout,
	}
}

// NewDeleteEnvironmentForRepositoryParamsWithContext creates a new DeleteEnvironmentForRepositoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEnvironmentForRepositoryParamsWithContext(ctx context.Context) *DeleteEnvironmentForRepositoryParams {
	var ()
	return &DeleteEnvironmentForRepositoryParams{

		Context: ctx,
	}
}

// NewDeleteEnvironmentForRepositoryParamsWithHTTPClient creates a new DeleteEnvironmentForRepositoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEnvironmentForRepositoryParamsWithHTTPClient(client *http.Client) *DeleteEnvironmentForRepositoryParams {
	var ()
	return &DeleteEnvironmentForRepositoryParams{
		HTTPClient: client,
	}
}

/*DeleteEnvironmentForRepositoryParams contains all the parameters to send to the API endpoint
for the delete environment for repository operation typically these are written to a http.Request
*/
type DeleteEnvironmentForRepositoryParams struct {

	/*EnvironmentUUID
	  The environment UUID.

	*/
	EnvironmentUUID string
	/*RepoSlug
	  The repository.

	*/
	RepoSlug string
	/*Username
	  The account.

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithTimeout(timeout time.Duration) *DeleteEnvironmentForRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithContext(ctx context.Context) *DeleteEnvironmentForRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithHTTPClient(client *http.Client) *DeleteEnvironmentForRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentUUID adds the environmentUUID to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithEnvironmentUUID(environmentUUID string) *DeleteEnvironmentForRepositoryParams {
	o.SetEnvironmentUUID(environmentUUID)
	return o
}

// SetEnvironmentUUID adds the environmentUuid to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetEnvironmentUUID(environmentUUID string) {
	o.EnvironmentUUID = environmentUUID
}

// WithRepoSlug adds the repoSlug to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithRepoSlug(repoSlug string) *DeleteEnvironmentForRepositoryParams {
	o.SetRepoSlug(repoSlug)
	return o
}

// SetRepoSlug adds the repoSlug to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetRepoSlug(repoSlug string) {
	o.RepoSlug = repoSlug
}

// WithUsername adds the username to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) WithUsername(username string) *DeleteEnvironmentForRepositoryParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the delete environment for repository params
func (o *DeleteEnvironmentForRepositoryParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnvironmentForRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environment_uuid
	if err := r.SetPathParam("environment_uuid", o.EnvironmentUUID); err != nil {
		return err
	}

	// path param repo_slug
	if err := r.SetPathParam("repo_slug", o.RepoSlug); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
