// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mjpitz/go-bitbucket/models"
)

// GetDeploymentsForRepositoryReader is a Reader for the GetDeploymentsForRepository structure.
type GetDeploymentsForRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeploymentsForRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeploymentsForRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeploymentsForRepositoryOK creates a GetDeploymentsForRepositoryOK with default headers values
func NewGetDeploymentsForRepositoryOK() *GetDeploymentsForRepositoryOK {
	return &GetDeploymentsForRepositoryOK{}
}

/*GetDeploymentsForRepositoryOK handles this case with default header values.

The matching deployments.
*/
type GetDeploymentsForRepositoryOK struct {
	Payload *models.PaginatedDeployments
}

func (o *GetDeploymentsForRepositoryOK) Error() string {
	return fmt.Sprintf("[GET /repositories/{workspace}/{repo_slug}/deployments/][%d] getDeploymentsForRepositoryOK  %+v", 200, o.Payload)
}

func (o *GetDeploymentsForRepositoryOK) GetPayload() *models.PaginatedDeployments {
	return o.Payload
}

func (o *GetDeploymentsForRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedDeployments)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
