// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PipelineRefTarget pipeline ref target
//
// swagger:model pipeline_ref_target
type PipelineRefTarget struct {
	PipelineTarget

	// commit
	Commit *Commit `json:"commit,omitempty"`

	// The name of the reference.
	RefName string `json:"ref_name,omitempty"`

	// The type of reference (branch/tag).
	// Enum: [branch tag named_branch bookmark]
	RefType string `json:"ref_type,omitempty"`

	// selector
	Selector *PipelineSelector `json:"selector,omitempty"`

	// a o1 additional properties
	AO1AdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PipelineRefTarget) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 PipelineTarget
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.PipelineTarget = aO0

	// AO1
	var dataAO1 struct {
		Commit *Commit `json:"commit,omitempty"`

		RefName string `json:"ref_name,omitempty"`

		RefType string `json:"ref_type,omitempty"`

		Selector *PipelineSelector `json:"selector,omitempty"`

		AO1AdditionalProperties map[string]interface{} `json:"-"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Commit = dataAO1.Commit

	m.RefName = dataAO1.RefName

	m.RefType = dataAO1.RefType

	m.Selector = dataAO1.Selector

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PipelineRefTarget) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.PipelineTarget)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Commit *Commit `json:"commit,omitempty"`

		RefName string `json:"ref_name,omitempty"`

		RefType string `json:"ref_type,omitempty"`

		Selector *PipelineSelector `json:"selector,omitempty"`

		AO1AdditionalProperties map[string]interface{} `json:"-"`
	}

	dataAO1.Commit = m.Commit

	dataAO1.RefName = m.RefName

	dataAO1.RefType = m.RefType

	dataAO1.Selector = m.Selector

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this pipeline ref target
func (m *PipelineRefTarget) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with PipelineTarget
	if err := m.PipelineTarget.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCommit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PipelineRefTarget) validateCommit(formats strfmt.Registry) error {

	if swag.IsZero(m.Commit) { // not required
		return nil
	}

	if m.Commit != nil {
		if err := m.Commit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("commit")
			}
			return err
		}
	}

	return nil
}

var pipelineRefTargetTypeRefTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["branch","tag","named_branch","bookmark"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pipelineRefTargetTypeRefTypePropEnum = append(pipelineRefTargetTypeRefTypePropEnum, v)
	}
}

// property enum
func (m *PipelineRefTarget) validateRefTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, pipelineRefTargetTypeRefTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PipelineRefTarget) validateRefType(formats strfmt.Registry) error {

	if swag.IsZero(m.RefType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRefTypeEnum("ref_type", "body", m.RefType); err != nil {
		return err
	}

	return nil
}

func (m *PipelineRefTarget) validateSelector(formats strfmt.Registry) error {

	if swag.IsZero(m.Selector) { // not required
		return nil
	}

	if m.Selector != nil {
		if err := m.Selector.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("selector")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PipelineRefTarget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PipelineRefTarget) UnmarshalBinary(b []byte) error {
	var res PipelineRefTarget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
