// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TeamPermission A user's permission for a given team.
//
// swagger:model team_permission
type TeamPermission struct {

	// permission
	// Enum: [admin collaborator]
	Permission string `json:"permission,omitempty"`

	// team
	Team *Team `json:"team,omitempty"`

	// type
	// Required: true
	Type *string `json:"type"`

	// user
	User *User `json:"user,omitempty"`

	// team permission additional properties
	TeamPermissionAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *TeamPermission) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// permission
		// Enum: [admin collaborator]
		Permission string `json:"permission,omitempty"`

		// team
		Team *Team `json:"team,omitempty"`

		// type
		// Required: true
		Type *string `json:"type"`

		// user
		User *User `json:"user,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv TeamPermission

	rcv.Permission = stage1.Permission
	rcv.Team = stage1.Team
	rcv.Type = stage1.Type
	rcv.User = stage1.User
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "permission")
	delete(stage2, "team")
	delete(stage2, "type")
	delete(stage2, "user")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.TeamPermissionAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m TeamPermission) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// permission
		// Enum: [admin collaborator]
		Permission string `json:"permission,omitempty"`

		// team
		Team *Team `json:"team,omitempty"`

		// type
		// Required: true
		Type *string `json:"type"`

		// user
		User *User `json:"user,omitempty"`
	}

	stage1.Permission = m.Permission
	stage1.Team = m.Team
	stage1.Type = m.Type
	stage1.User = m.User

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.TeamPermissionAdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.TeamPermissionAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this team permission
func (m *TeamPermission) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePermission(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTeam(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var teamPermissionTypePermissionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["admin","collaborator"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		teamPermissionTypePermissionPropEnum = append(teamPermissionTypePermissionPropEnum, v)
	}
}

const (

	// TeamPermissionPermissionAdmin captures enum value "admin"
	TeamPermissionPermissionAdmin string = "admin"

	// TeamPermissionPermissionCollaborator captures enum value "collaborator"
	TeamPermissionPermissionCollaborator string = "collaborator"
)

// prop value enum
func (m *TeamPermission) validatePermissionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, teamPermissionTypePermissionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TeamPermission) validatePermission(formats strfmt.Registry) error {

	if swag.IsZero(m.Permission) { // not required
		return nil
	}

	// value enum
	if err := m.validatePermissionEnum("permission", "body", m.Permission); err != nil {
		return err
	}

	return nil
}

func (m *TeamPermission) validateTeam(formats strfmt.Registry) error {

	if swag.IsZero(m.Team) { // not required
		return nil
	}

	if m.Team != nil {
		if err := m.Team.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("team")
			}
			return err
		}
	}

	return nil
}

func (m *TeamPermission) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *TeamPermission) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TeamPermission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TeamPermission) UnmarshalBinary(b []byte) error {
	var res TeamPermission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
