// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Team team
//
// swagger:model team
type Team struct {
	Account

	TeamAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Team) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Account
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Account = aO0

	// AO1
	var aO1 TeamAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TeamAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Team) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Account)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TeamAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this team
func (m *Team) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Account
	if err := m.Account.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TeamAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Team) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Team) UnmarshalBinary(b []byte) error {
	var res Team
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TeamAllOf1 A team object.
//
// swagger:model TeamAllOf1
type TeamAllOf1 interface{}
